### ISSUE TITLE
External disk icon looks fuzzy(low-res)

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell-theme#13]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
* Distribution - (run ```lsb_release -a```)
18.04
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
3.22.29-3ubuntu1
 * Desktop environment - 
GNOME
 * Pop version - (run ```head -n 3 /usr/share/gnome-shell/theme/pop.css```)
4.0.0
 ```
**Actual issue**
The icon that appears with the notification when plugging in an external drive looks fuzzy/low-resolution.

![fuzzy](https://user-images.githubusercontent.com/7460774/38885332-e2486500-422f-11e8-8ddc-aefbea6b7d4b.png)

**Expected behavior**
Icon does not look fuzzy/low-resolution.

**Other Note (feature-request, question, etc...)**
In case I'm just loosing my eyesight or something, I had @btkostner confirm he thought so as well.

**Comment by isantop** [comment]
It looks like almost all of the theme-provided notification icons are a bit fuzzy, likely to being a single pixel off on size. Should be as easy as increasing/decreasing the size by 1px.
