### ISSUE TITLE
Alt-tab multiple window cue missing

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell-theme#16]
```
 * Distribution - (run ```lsb_release -a```)
Pop!_OS 18.04
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
3.22.29-3ubuntu1
 * Desktop environment - 
Gnome
 * Pop version - (run ```head -n 3 /usr/share/gnome-shell/theme/pop.css```)
4.0.0
 ```
**Actual issue**
A visual cue does not exist to show when multiple windows of a program are open. In Pop!_OS 17.10 an arrow shows underneath each program that has multiple windows open.

**Other Note (feature-request, question, etc...)**
While I understand part of this theme is getting rid of the arrows, I think by removing them on this screen, a feature is lost(is a "feature regression" a thing?). I think some sort of cue should exist.

**Comment by isantop** [comment]
> While I understand part of this theme is getting rid of the arrows, I think by removing them on this screen, a feature is lost(is a "feature regression" a thing?). I think some sort of cue should exist.
Agreed. It's only a "feature" on the top panel, which tends to get cluttered with arrows. We wouldn't want people muttering that we're getting rid of usability!
