### ISSUE TITLE
User menu selections do not highlight under mouse

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell-theme#2]
```
 * Distribution - (run ```lsb_release -a```)
Pop!_OS 18.04
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 3.22.29-3ubuntu1
 * Desktop environment - Gnome
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
3.1.0
 ```

**Related Application and/or Shell theming (or name of widget)**
User menu

**Actual issue**
In the user menu, the sub-menu selections no longer highlight when the mouse hovers over the entry (or when scrolling through on the keyboard). It might be that it is still highlighting but highlighting to the background color. 

![usermenu](https://user-images.githubusercontent.com/7460774/38748100-452a4554-3f0a-11e8-89aa-2b6ea79ed3a2.png)

**Expected behavior**
My mouse(or keyboard) should highlight submenus just like they do in the menus(wifi,bluetooth,power,user)

**Comment by isantop** [comment]
They do highlight, but the highlight color is the same color as the submenu background. @brs17 @cassidyjames Do you guys think the highlight should be lighter or darker than the submenu?

**Comment by brs17** [comment]
Seeing that when selecting internet/bluetooth/battery the highlight is darker, I would lean towards darker but I think it'll come down to seeing how it actually looks.

**Comment by isantop** [comment]
@cassidyjames agrees. It is committed
