### ISSUE TITLE
App-Folder not fully outlined

### ISSUE THREAD

**Issue by OliverScholtz** [pop-os/gnome-shell-theme#20]
**Pop OS Beta Ubuntu 18.04**

```
 * In Activity mode open App-Folder:
 * System, Utility, Office
 * ... Folder not fully outlined
 * the outline down is invisible.
 ```

**Comment by isantop** [comment]
Can you post a screenshot? I can't seem to replicate this here.

**Comment by OliverScholtz** [comment]
of course

<a href="https://www.pic-upload.de/view-35195113/Capturadepantallade2018-04-1922-12-38.png.html" target="_blank"><img src="https://www2.pic-upload.de/thumb/35195113/Capturadepantallade2018-04-1922-12-38.png" title="Bilder oder Fotos hochladen"></a>

<a href="https://www.pic-upload.de/view-35195121/Capturadepantallade2018-04-1922-13-02.png.html" target="_blank"><img src="https://www2.pic-upload.de/thumb/35195121/Capturadepantallade2018-04-1922-13-02.png" title="Bilder oder Fotos hochladen"></a>

[https://www.pic-upload.de/view-35195113/Capturadepantallade2018-04-1922-12-38.png.html](url)

[https://www.pic-upload.de/view-35195121/Capturadepantallade2018-04-1922-13-02.png.html](url)

**Comment by OliverScholtz** [comment]
this issue has to checked with standard wide screen Notebook screens with poor resolution: I think I have 1280 * 1024. The fonts are big on this screens and probably the cause of the only 1px cut. Please check it, maybe reduce a little bit the margin or spacing can resolve it.

**Comment by OliverScholtz** [comment]
I tried to resolve it with hacking the CSS. But I couldn't. So I put in the app-folder line:

border: 0px solid colour
radius: 2px

I think this has to been reported as bug in Gnome/// gnome-shell .... if not yet reported......

Meanwhile I think a graphical (PNG file) solution could manage this issue.

**Comment by aden-young** [comment]
This bug is still active on my system after a fresh install

**Comment by OliverScholtz** [comment]
This Bug apears when you have more Icons (Apps) in the Icon-Overview and is created a new page for scroll down....
