### ISSUE TITLE
8 icons in dash overlap on 1600×900

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gnome-shell-theme#23]
Doesn't happen with 7 or 9 icons. But some spacing thing is probably causing this.

![screenshot from 2018-04-26 14-02-31](https://user-images.githubusercontent.com/611168/39329205-d6998b4e-495a-11e8-8912-6f60babe1524.png)

**Comment by axelmeunier** [comment]
Happens with 10 icons as well in my install...
![capture d ecran de 2018-04-30 17-39-35](https://user-images.githubusercontent.com/3244556/39436218-ac1f59a2-4c9d-11e8-8438-063dff5544cd.png)

**Comment by isantop** [comment]
Something appears to be preventing the Dash from shrinking the way it's supposed to when the dashboard is full.

**Comment by sklei4** [comment]
I'm having this problem too.

**Comment by sklei4** [comment]
I'm not having this problem today after updates.

**Comment by chriswere** [comment]
I'm afraid the same problem remains for me too. Do we have any news on when a fix might be rolled out?
