### ISSUE TITLE
Loading spinner next to App Menu is huge

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gnome-shell-theme#25]
When an app is in the "loading" state, like soon after launching, the spinner next to the app menu looks oversized:

![screenshot from 2018-04-30 11-08-12](https://user-images.githubusercontent.com/611168/39440083-0598a6e6-4c67-11e8-8a51-d4350e47493d.png)

**Comment by isantop** [comment]
This seems to be related to the Shell not fully respecting and re-sizing components when the DPI is changed. If I start out on a LoDPI external monitor and switch to the HiDPI internal, the spinner is too small. 

Does this happen to you when you avoid plugging or unplugging an external monitor?
