### ISSUE TITLE
Activities overview - workspaces are broken without Always show workspaces extension

### ISSUE THREAD

**Issue by kristho91** [pop-os/gnome-shell-theme#26]
**Reporter info**

```
 * Distribution - Pop!_OS 18.04 LTS
 * Gtk+ 3.0 version - 3.22.30-1ubuntu1
 * Desktop environment - GNOME 3.28.1
 * Pop version - 4.0.0
 ```

**Related Application and/or Shell theming (or name of widget)**
Workspace switcher

**Actual issue**
When "Always show workspaces" is ON the workspace switcher in Activities is correctly all locked in place.
If "Always show workspaces" is OFF the workspace switcher is not sliding to the side (like in Adwaita fx) but is being pushed even more out from the right edge. And on hover it makes everything in the Activities overview jump around.

**Steps to reproduce**
Use default settings on a fresh install.
Install gnome-tweaks
Deactivate "Always show workspaces" extension
Go to Activities overview and mouse over the workspace-switcher.

**Expected behavior**
It's expected to slide the workspace-switcher to the right side and slide out on mouse over.

**Comment by evertiro** [comment]
I haven't been able to replicate this issue on 18.10, is it still occurring on Cosmic, or has it been resolved?

**Comment by isantop** [comment]
I can't replicate this either. I'm going to go ahead and close this.
