### ISSUE TITLE
suggestion #1 Panel

### ISSUE THREAD

**Issue by OliverScholtz** [pop-os/gnome-shell-theme#28]
For considering, please try...

**

#panel {
  background-color: rgba(37,34,32, 0.8); /*#252220;*/
  box-shadow: 0 3px 3px rgba(0, 0, 0, 0.24), 0 3px 3px rgba(0, 0, 0, 0.345);
......
}

#panel.solid {
  background-color: #252220;
  box-shadow: none;
}

**

Thank you for considering and trying

**Comment by isantop** [comment]
It doesn't really fit in with the Pop visual style to have the panel be transparent under most circumstances. Thanks for your suggestion though!
