### ISSUE TITLE
Icon-Overview Button on the left side

### ISSUE THREAD

**Issue by OliverScholtz** [pop-os/gnome-shell-theme#29]
![captura de pantalla de 2018-05-10 23-14-46](https://user-images.githubusercontent.com/38477330/39894943-cf2e4198-54a8-11e8-8fa1-99186eb72b00.png)

**Comment by isantop** [comment]
I can't seem to replicate this here on any setups. What extensions do you have enabled? My guess is that this is being added by one of them.

**Comment by OliverScholtz** [comment]
No. No extensións are added. Everything it's all as default.
Set 1 - 4 icons and I think you will reproduce this Bug.

**Comment by OliverScholtz** [comment]
I think that this couldn't be correct:

> .show-apps-icon {
>   padding-right: 16px;
> }

I changed it for:

```
.show-apps-icon {
  padding: 4px;
}
```

This works for me.

**Comment by brs17** [comment]
I can confirm this, it appears on a fresh install of Pop!_OS.
