### ISSUE TITLE
Activies menu underlign replaced with orange dot in corner

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell-theme#3]
```
 * Distribution - (run ```lsb_release -a```)
Pop!_OS 18.04
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 3.22.29-3ubuntu1
 * Desktop environment - Gnome
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
3.1.0
 ```
**Actual issue**
When going into the Activities view, `Activities` is no longer underlined in orange but there is a little orange mark around the corner.
![activities_menu](https://user-images.githubusercontent.com/7460774/38751442-5cf73bfa-3f15-11e8-95f2-a4a03692f270.png)

**Steps to reproduce**
Click `Activities`

**Expected behavior**
If this theme update purposefully removes the underline, then perhaps the underline for the clock and user menu should be removed as well. Otherwise `Activities` should be underlined.

**Comment by isantop** [comment]
Yep, this is bug due to the fact that the current underlines are `box-shadows` not borders. This is currently fixed in 4b47a7cead03e67ac0f3a654dca2e5f7605c682b
