### ISSUE TITLE
On screen keyboard cut off

### ISSUE THREAD

**Issue by jonchampagne** [pop-os/gnome-shell-theme#34]
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

 * Gtk+ 3.0 version - (run ```pacman -Q gtk3```)
gtk3 3.22.30-1

 * Desktop environment - (run ```pacman -Q gnome-shell```) 
gnome-shell 3.28.2-1
 * Pop version - (run ```head -n 3 /usr/share/gnome-shell/theme/pop.css```)
N/A
 ```

**Related Application and/or Shell theming (or name of widget)**
On screen keyboard

**Actual issue**
On screen keyboard is cut off in landscape screen orientation. 

**Steps to reproduce**
Have a touchscreen device (tested with dell latitude 7375 2-in-1)
Have keyboard appear in the normal fastion (eg touch a gtk text field like terminal or gedit), or swipe up from bottom of screen to reveal keyboard

**Expected behavior**
Keyboard appears and all keys are visible and touchable

**Behavior in Adwaita**
Keyboard appears fine

**Other Note (feature-request, question, etc...)**
Screenshots included.
OSK pop theme:
![keyboard cut off landscape pop](https://user-images.githubusercontent.com/1485633/40270712-0d0684c2-5b60-11e8-826b-e669d47db2c1.png)

OSK pop compact theme:
![keyboard cut off landscape pop compact](https://user-images.githubusercontent.com/1485633/40270716-1eec92e4-5b60-11e8-8394-86fbca5655c2.png)

OSK pop theme portrait display:
![keyboard fine portrait pop](https://user-images.githubusercontent.com/1485633/40270721-3270c984-5b60-11e8-941e-baa4c1f6d1cf.png)

OSK adwitta theme:
![keyboard fine landscape adwitta](https://user-images.githubusercontent.com/1485633/40270722-3bff408e-5b60-11e8-921e-3a083d350a91.png)

**Comment by RussianNeuroMancer** [comment]
Same issue here, except on devices I get this issue with Adwaita theme too. Seems like fonts scaling setting in Gnome Tweak Tool affect OSK in a wrong way.

**Comment by brs17** [comment]
With the patch mentioned above, this should no longer be an issue.
