### ISSUE TITLE
Topbar aren't changing the height when using slim theme

### ISSUE THREAD

**Issue by yuritoledo** [pop-os/gnome-shell-theme#5]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.04 LTS (Testing)
Release:	18.04
Codename:	bionic

 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
libgtk-3-0:
  Instalado: 3.22.29-3ubuntu1
  Candidato: 3.22.29-3ubuntu1
  Tabela de versão:
 *** 3.22.29-3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
 * Desktop environment - gnome
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
/***************************
   Pop!_GTK+ Version 3.1.0 
 ***************************/

**Related Application and/or Shell theming (or name of widget)**

Pop Slim!

**Actual issue**
Pop_slim theme (normal and dark) aren't reducing the topbar height, just the fonts; the height keep the same as slim theme default.

**Steps to reproduce**
Just switch the themes

**Expected behavior**
Change the font and topbar height.

**Comment by isantop** [comment]
Thanks for your issue! This is fixed in Pop_GNOME 4.0, which will be the default in Pop_OS 18.04. The 3.1.0 version is actually that bundled with the gtk-theme repository.
