### ISSUE TITLE
Not Responding dialog has no shadow or background mask

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gnome-shell-theme#6]
Saw something weird with the new theme today: the Not Responding shell dialog had no shadow at all, and no background mask. This doesn't look great and means it gets somewhat lost in white windows, which is probably not ideal.

![screenshot from 2018-04-13 23-14-08](https://user-images.githubusercontent.com/611168/38764683-ddd066d8-3f70-11e8-8fa5-9f6a19f777ee.png)

**Comment by isantop** [comment]
This isn;'t a bug with the theme, because applications should never stop responding. Marking wontfix.

/s :D
