### ISSUE TITLE
Terminal scrolls when it loses focus

### ISSUE THREAD

**Issue by jonathandturner** [pop-os/gnome-shell-theme#61]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.10
Release:	18.10
Codename:	cosmic

 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)

libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

 * Desktop environment - 

Default (GNOME)

 * Pop version - (run ```head -n 3 /usr/share/gnome-shell/theme/pop.css```)

/***************************
 * Pop!_GNOME+ Version 4.0.2 *
 ***************************/

 ```

**Related Application and/or Shell theming (or name of widget)**

Terminal, default theme

**Actual issue**

Click away from terminal and back to terminal changes scroll value

**Steps to reproduce**

1) Work in the terminal until you have a full terminal of text
2) Click away from the terminal to another app, say Firefox
3) Click back to the terminal

**Expected behavior**

The scroll value stays the same and the contents of the terminal doesn't move around.

**Behavior in Adwaita**

## Before clicking away
![screenshot from 2018-10-21 05-58-05](https://user-images.githubusercontent.com/547158/47258335-57824a80-d4f6-11e8-8ccb-6610c975a2aa.png)

## After clicking away
![screenshot from 2018-10-21 06-00-01](https://user-images.githubusercontent.com/547158/47258355-94e6d800-d4f6-11e8-9ad1-431aefed0861.png)

**Other Note (feature-request, question, etc...)**

Apologies if this isn't the right repo to file the issue, it's the closest one I could find.

**Comment by brs17** [comment]
Thank you for filing this issue. This is a duplicate issue of https://github.com/pop-os/gtk-theme/issues/217 which is being addressed here: https://github.com/pop-os/gtk-theme/pull/225 .
