### ISSUE TITLE
White on white links in Evolution

### ISSUE THREAD

**Issue by nicojx** [pop-os/gnome-shell-theme#62]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

```
 * Distribution - Ubuntu 18.10
 * Gtk+ 3.0 version - 3.24.1-1ubuntu2
 * Desktop environment - GNOME Shell 3.30.1
 * Pop version - Pop!_GNOME+ Version 4.0.2
 ```

**Related Application and/or Shell theming (or name of widget)**
Evolution 

**Actual issue**
Text of most embedded links in emails displayed in Evolution appear white on white, i.e. the text isn't visible at all unless the text is selected.  All Pop-themes affected (light, slim, etc.).

**Steps to reproduce**
Install 18.10 Ubuntu, Pop theme and Evolution. Select Pop theme for "Applications". Open an email with embedded links. 

**Expected behavior**
Links are visible, possibly in a different colour to standard text.

**Behavior in Adwaita**
Links are visible. Text appears in blue.

**Other Note (feature-request, question, etc...)**

![image](https://user-images.githubusercontent.com/1081603/47267593-05fdae00-d53e-11e8-9322-548d855c801d.png)

**Comment by nicojx** [comment]
Reposted this in gtk-theme, where it seems more appropriate...

**Comment by jackpot51** [comment]
Closing, as it will be dealt with in https://github.com/pop-os/gtk-theme/issues/240
