### ISSUE TITLE
Keyboard layout indicator blank (does not show the selected language)

### ISSUE THREAD

**Issue by skopjanecot** [pop-os/gnome-shell-theme#70]
Distribution - Pop!_OS 18.04 LTS
Gtk+ 3.0 version - 3.22.30-1ubuntu1
Desktop environment - Gnome
Pop version - Pop!_GNOME+ Version 4.0.2**

Actual issue
As the title says, the keyboard layout indicator is not showing the chosen language in the taskbar. When I click on the place where it usually is, it does bring the pop up window with the list of languages, but none of them seems selected and with a black dot on the side. After clicking on one of the languages the indicator will show the selected language for a while, but it will disappear again eventually.

![screenshot from 2019-01-11 11-24-28](https://user-images.githubusercontent.com/46635826/51079180-e43a4000-16c2-11e9-8ee7-ac829ae777c1.png)
![screenshot from 2019-01-11 11-24-49](https://user-images.githubusercontent.com/46635826/51079181-e6040380-16c2-11e9-857c-0692869d6a9d.png)

**Comment by isantop** [comment]
Does this issue only occur with the Pop theme selected, or do you also see this problem when you use other themes? Note that the Shell theme is different from the GTK Theme, and can be selected in GNOME Tweaks by choosing the "Shell" theme in the "Appearance" category.

**Comment by skopjanecot** [comment]
The issue persist with all other themes. 
I just realized that the indicator goes blank when I log into my google account using Firefox with both  the saved login and without it. It goes blank immediately as the password input dialog loads. When using a saved login for another site, the indicator shows the language normally.

**Comment by skopjanecot** [comment]
Just an update. The indicator goes blank on ebay as well, as soon as I switch to the password input field. It seems like it is an issue with the password protection protocols.

**Comment by isantop** [comment]
If the problem happens with other themes, then it's likely a glitch in GNOME Shell or with the indicators in question. It's not a problem with the Pop Theme.

**Comment by skopjanecot** [comment]
I am not sure the issue should be closed. I might have made a mistake in terms of what you call a theme. I am new to Linux. I have tried this issue with Pop-dark and Adwaita. I think the Pop Theme shell is the only one installed on my system, since I cannot choose anything else as seen on the screenshot.
![screenshot from 2019-01-16 18-13-59](https://user-images.githubusercontent.com/46635826/51266180-d20a1b80-19ba-11e9-9806-88455e7c9b9e.png)
